import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  Banknote,
  Bell,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  CalendarClock,
  CheckCircle2,
  CheckSquare,
  ClipboardList,
  Cog,
  Coins,
  Database,
  FileBox,
  FileSearch,
  FileText,
  GitBranch,
  GitCompare,
  Headphones,
  Image as ImageIcon,
  Inbox,
  LayoutDashboard,
  LineChart,
  ListChecks,
  Megaphone,
  MessageSquare,
  Newspaper,
  Package,
  PackageCheck,
  Plug,
  Receipt,
  RotateCcw,
  Route as RouteIcon,
  ScrollText,
  Settings,
  Shapes,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Store,
  Tags,
  Target,
  Truck,
  Users,
  Wallet,
  Wrench,
} from "lucide-react";

export type RouteSection = "core" | "departments" | "intelligence" | "system";
export type OptionalFeature = "inventory";
export type BadgeKind = "inbox" | "tasks" | "alerts" | "approvals";

export type RouteMeta = {
  /** Stable id, e.g. "finance.orders-margin". Frozen contract for later phases. */
  id: string;
  path: string;
  /** Short label for sidebar items and tabs. */
  label: string;
  /** Page heading. Usually the department/page name. */
  title: string;
  /** One-line operator purpose ("the question this page answers"). */
  description: string;
  icon: LucideIcon;
  section: RouteSection;
  /** Department id for subpages; undefined for top-level. */
  parentId?: string;
  /** Department root overview page. */
  isOverview?: boolean;
  badge?: BadgeKind;
  optionalFeature?: OptionalFeature;
  /** Implementation status, surfaced honestly in placeholder pages. */
  build: "built" | "placeholder";
};

/**
 * Full route registry. Single source of truth for navigation, breadcrumbs,
 * page headings, command-palette route search, and active-state derivation.
 */
export const ROUTES: RouteMeta[] = [
  // ── Command Center ────────────────────────────────────────────────
  {
    id: "command-center",
    path: "/command-center",
    label: "Command Center",
    title: "Command Center",
    description: "What is happening across the brand, and what needs attention now?",
    icon: LayoutDashboard,
    section: "core",
    isOverview: true,
    build: "built",
  },
  {
    id: "command-center.daily-brief",
    path: "/command-center/daily-brief",
    label: "Daily Brief",
    title: "Daily Brief",
    description: "What happened yesterday, what matters today, and what the team should do.",
    icon: Newspaper,
    section: "core",
    parentId: "command-center",
    build: "placeholder",
  },
  {
    id: "command-center.insights",
    path: "/command-center/insights",
    label: "Insights",
    title: "Cross-department Insights",
    description: "Findings ranked by impact, confidence, freshness, and status.",
    icon: Sparkles,
    section: "core",
    parentId: "command-center",
    build: "placeholder",
  },
  {
    id: "command-center.alerts",
    path: "/command-center/alerts",
    label: "Alerts",
    title: "Alerts",
    description: "Operational alert inbox with severity, scope, owner, and related trace.",
    icon: AlertTriangle,
    section: "core",
    parentId: "command-center",
    build: "placeholder",
  },

  // ── Inbox ─────────────────────────────────────────────────────────
  {
    id: "inbox",
    path: "/inbox",
    label: "Inbox",
    title: "Inbox",
    description: "Which items require a person's attention?",
    icon: Inbox,
    section: "core",
    isOverview: true,
    badge: "inbox",
    build: "placeholder",
  },
  {
    id: "inbox.customer-tickets",
    path: "/inbox/customer-tickets",
    label: "Customer Tickets",
    title: "Customer Tickets",
    description: "Escalated, reopened, VIP, negative-sentiment, overdue, and failed-automation tickets.",
    icon: Headphones,
    section: "core",
    parentId: "inbox",
    build: "placeholder",
  },
  {
    id: "inbox.approvals",
    path: "/inbox/approvals",
    label: "Approvals",
    title: "Approvals",
    description: "Discounts, refunds, exceptional messages, and configuration changes awaiting a decision.",
    icon: ShieldCheck,
    section: "core",
    parentId: "inbox",
    badge: "approvals",
    build: "placeholder",
  },
  {
    id: "inbox.mentions",
    path: "/inbox/mentions",
    label: "Mentions",
    title: "Mentions & Assignments",
    description: "Human/agent mentions, assigned comments, and requested reviews.",
    icon: MessageSquare,
    section: "core",
    parentId: "inbox",
    build: "placeholder",
  },
  {
    id: "inbox.system-alerts",
    path: "/inbox/system-alerts",
    label: "System Alerts",
    title: "System Alerts",
    description: "Connector, freshness, queue, runtime, and delivery problems with recommended next steps.",
    icon: Bell,
    section: "core",
    parentId: "inbox",
    build: "placeholder",
  },

  // ── My Tasks ──────────────────────────────────────────────────────
  {
    id: "tasks",
    path: "/tasks",
    label: "My Tasks",
    title: "My Tasks",
    description: "What do I need to do, by when, and why?",
    icon: CheckSquare,
    section: "core",
    isOverview: true,
    badge: "tasks",
    build: "built",
  },
  {
    id: "tasks.my-work",
    path: "/tasks/my-work",
    label: "My Work",
    title: "My Work",
    description: "Your assigned tasks across List, Board, and Today views.",
    icon: ListChecks,
    section: "core",
    parentId: "tasks",
    build: "placeholder",
  },
  {
    id: "tasks.team",
    path: "/tasks/team",
    label: "Team",
    title: "Team Workload",
    description: "Team workload and blocked tasks — not surveillance metrics.",
    icon: Users,
    section: "core",
    parentId: "tasks",
    build: "placeholder",
  },
  {
    id: "tasks.completed",
    path: "/tasks/completed",
    label: "Completed",
    title: "Completed Tasks",
    description: "Searchable task history with outcome and related records.",
    icon: CheckCircle2,
    section: "core",
    parentId: "tasks",
    build: "placeholder",
  },

  // ── Customer Service ──────────────────────────────────────────────
  {
    id: "customer-service",
    path: "/customer-service",
    label: "Overview",
    title: "Customer Service",
    description: "Is customer service healthy, and where is automation failing?",
    icon: Headphones,
    section: "departments",
    isOverview: true,
    build: "built",
  },
  {
    id: "customer-service.tickets",
    path: "/customer-service/tickets",
    label: "Tickets",
    title: "Tickets",
    description: "The full ticket dataset with saved views and a detail drawer.",
    icon: ClipboardList,
    section: "departments",
    parentId: "customer-service",
    build: "placeholder",
  },
  {
    id: "customer-service.automations",
    path: "/customer-service/automations",
    label: "Automations",
    title: "Automations",
    description: "Automation flows with trigger, scope, success, escalation, and failure.",
    icon: GitBranch,
    section: "departments",
    parentId: "customer-service",
    build: "placeholder",
  },
  {
    id: "customer-service.prompts",
    path: "/customer-service/prompts",
    label: "Prompts",
    title: "Prompt Library",
    description: "Prompts grouped by automation and step, with versions and test cases.",
    icon: ScrollText,
    section: "departments",
    parentId: "customer-service",
    build: "placeholder",
  },
  {
    id: "customer-service.approvals",
    path: "/customer-service/approvals",
    label: "Approvals",
    title: "CS Approvals",
    description: "Approval queue with CS context, policy comparison, and cohort filters.",
    icon: ShieldCheck,
    section: "departments",
    parentId: "customer-service",
    build: "placeholder",
  },
  {
    id: "customer-service.quality",
    path: "/customer-service/quality",
    label: "Quality",
    title: "Quality Review",
    description: "Sampled conversations, deviations, and grounding issues for review.",
    icon: ShieldCheck,
    section: "departments",
    parentId: "customer-service",
    build: "placeholder",
  },

  // ── Finance ───────────────────────────────────────────────────────
  {
    id: "finance",
    path: "/finance",
    label: "Overview",
    title: "Finance",
    description: "What is the brand actually earning, and how trustworthy is the number?",
    icon: Wallet,
    section: "departments",
    isOverview: true,
    build: "built",
  },
  {
    id: "finance.profit",
    path: "/finance/profit",
    label: "Profit",
    title: "Profit",
    description: "Contribution-margin trends, component breakdown, and driver analysis.",
    icon: LineChart,
    section: "departments",
    parentId: "finance",
    build: "placeholder",
  },
  {
    id: "finance.orders-margin",
    path: "/finance/orders-margin",
    label: "Orders & Margin",
    title: "Orders & Margin",
    description: "Order-level margin with cost evidence, attribution, and source timestamps.",
    icon: Receipt,
    section: "departments",
    parentId: "finance",
    build: "placeholder",
  },
  {
    id: "finance.spend-roas",
    path: "/finance/spend-roas",
    label: "Spend & ROAS",
    title: "Spend & ROAS",
    description: "Channel and campaign spend, attributed revenue, ROAS, MER, and CAC.",
    icon: Target,
    section: "departments",
    parentId: "finance",
    build: "placeholder",
  },
  {
    id: "finance.costs-fees",
    path: "/finance/costs-fees",
    label: "Costs & Fees",
    title: "Costs & Fees",
    description: "Cost catalog and trends; missing or estimated values made prominent.",
    icon: Coins,
    section: "departments",
    parentId: "finance",
    build: "placeholder",
  },
  {
    id: "finance.payouts",
    path: "/finance/payouts",
    label: "Payouts",
    title: "Payouts",
    description: "Payout schedule and reconciliation: expected, pending, paid, failed, variance.",
    icon: Banknote,
    section: "departments",
    parentId: "finance",
    build: "placeholder",
  },
  {
    id: "finance.reconciliation",
    path: "/finance/reconciliation",
    label: "Reconciliation",
    title: "Reconciliation",
    description: "Data-trust workspace: connections, unmatched transactions, missing COGS, gaps.",
    icon: GitCompare,
    section: "departments",
    parentId: "finance",
    build: "placeholder",
  },

  // ── Marketing ─────────────────────────────────────────────────────
  {
    id: "marketing",
    path: "/marketing",
    label: "Overview",
    title: "Marketing",
    description: "Which growth activities create profitable demand, and what is deteriorating?",
    icon: Megaphone,
    section: "departments",
    isOverview: true,
    build: "placeholder",
  },
  {
    id: "marketing.campaigns",
    path: "/marketing/campaigns",
    label: "Campaigns",
    title: "Campaigns",
    description: "Channel → campaign → ad set → ad with spend, revenue, margin, ROAS, and trend.",
    icon: Target,
    section: "departments",
    parentId: "marketing",
    build: "placeholder",
  },
  {
    id: "marketing.creatives",
    path: "/marketing/creatives",
    label: "Creatives",
    title: "Creatives",
    description: "Visual library with hook, format, spend, revenue, ROAS, and fatigue.",
    icon: ImageIcon,
    section: "departments",
    parentId: "marketing",
    build: "placeholder",
  },
  {
    id: "marketing.content",
    path: "/marketing/content",
    label: "Content",
    title: "Content",
    description: "Calendar and pipeline: idea, drafting, review, scheduled, published.",
    icon: FileText,
    section: "departments",
    parentId: "marketing",
    build: "placeholder",
  },
  {
    id: "marketing.audiences",
    path: "/marketing/audiences",
    label: "Audiences",
    title: "Audiences",
    description: "Segment definitions, channel usage, size, overlap, and performance.",
    icon: Users,
    section: "departments",
    parentId: "marketing",
    build: "placeholder",
  },
  {
    id: "marketing.research",
    path: "/marketing/research",
    label: "Research",
    title: "Marketing Research",
    description: "Competitor, trend, offer, and creative research with findings and recommendations.",
    icon: FileSearch,
    section: "departments",
    parentId: "marketing",
    build: "placeholder",
  },

  // ── Commerce ──────────────────────────────────────────────────────
  {
    id: "commerce",
    path: "/commerce",
    label: "Overview",
    title: "Commerce",
    description: "What is selling, to whom, and where are commercial outcomes changing?",
    icon: ShoppingCart,
    section: "departments",
    isOverview: true,
    build: "placeholder",
  },
  {
    id: "commerce.orders",
    path: "/commerce/orders",
    label: "Orders",
    title: "Orders",
    description: "Primary orders table with status, fulfilment, margin, risk, and tickets.",
    icon: ShoppingBag,
    section: "departments",
    parentId: "commerce",
    build: "placeholder",
  },
  {
    id: "commerce.products",
    path: "/commerce/products",
    label: "Products",
    title: "Products",
    description: "Product performance across revenue, margin, returns, ad spend, and supplier.",
    icon: Package,
    section: "departments",
    parentId: "commerce",
    build: "placeholder",
  },
  {
    id: "commerce.customers",
    path: "/commerce/customers",
    label: "Customers",
    title: "Customers",
    description: "Customers with lifetime value, segment, ticket history, and refund risk.",
    icon: Users,
    section: "departments",
    parentId: "commerce",
    build: "placeholder",
  },
  {
    id: "commerce.discounts",
    path: "/commerce/discounts",
    label: "Discounts",
    title: "Discounts",
    description: "Codes and automatic discounts with source, usage, and margin impact.",
    icon: Tags,
    section: "departments",
    parentId: "commerce",
    build: "placeholder",
  },

  // ── Operations ────────────────────────────────────────────────────
  {
    id: "operations",
    path: "/operations",
    label: "Overview",
    title: "Operations",
    description: "Can orders be fulfilled reliably, and which exceptions threaten customers or margin?",
    icon: Truck,
    section: "departments",
    isOverview: true,
    build: "placeholder",
  },
  {
    id: "operations.fulfilment",
    path: "/operations/fulfilment",
    label: "Fulfilment",
    title: "Fulfilment",
    description: "Fulfilment table with provider, promised vs shipped dates, tracking, and delay.",
    icon: PackageCheck,
    section: "departments",
    parentId: "operations",
    build: "placeholder",
  },
  {
    id: "operations.returns",
    path: "/operations/returns",
    label: "Returns",
    title: "Returns",
    description: "Return/refund requests with reason, value, margin impact, and approval routing.",
    icon: RotateCcw,
    section: "departments",
    parentId: "operations",
    build: "placeholder",
  },
  {
    id: "operations.suppliers",
    path: "/operations/suppliers",
    label: "Suppliers",
    title: "Suppliers",
    description: "Supplier scorecards across delivery, defect, cost, and communication.",
    icon: Boxes,
    section: "departments",
    parentId: "operations",
    build: "placeholder",
  },
  {
    id: "operations.inventory",
    path: "/operations/inventory",
    label: "Inventory",
    title: "Inventory",
    description: "Stock, incoming, sell-through, days cover, and reorder risk. Optional module.",
    icon: Database,
    section: "departments",
    parentId: "operations",
    optionalFeature: "inventory",
    build: "placeholder",
  },
  {
    id: "operations.exceptions",
    path: "/operations/exceptions",
    label: "Exceptions",
    title: "Exceptions",
    description: "Central operational queue: late fulfilment, missing tracking, supplier delay.",
    icon: AlertTriangle,
    section: "departments",
    parentId: "operations",
    build: "placeholder",
  },

  // ── Agents ────────────────────────────────────────────────────────
  {
    id: "agents",
    path: "/agents",
    label: "Overview",
    title: "Agents",
    description: "What are the agents doing, how well, and where do they need supervision?",
    icon: Bot,
    section: "intelligence",
    isOverview: true,
    build: "placeholder",
  },
  {
    id: "agents.list",
    path: "/agents/list",
    label: "Agents",
    title: "Agents",
    description: "Agent roster with purpose, autonomy mode, tools, schedule, and performance.",
    icon: Bot,
    section: "intelligence",
    parentId: "agents",
    build: "placeholder",
  },
  {
    id: "agents.runs",
    path: "/agents/runs",
    label: "Runs",
    title: "Runs",
    description: "Run history with trigger, duration, tools, actions, approvals, and result.",
    icon: RouteIcon,
    section: "intelligence",
    parentId: "agents",
    build: "placeholder",
  },
  {
    id: "agents.tools-permissions",
    path: "/agents/tools-permissions",
    label: "Tools & Permissions",
    title: "Tools & Permissions",
    description: "Capability matrix: denied, read, bounded write, approval required, unrestricted.",
    icon: Wrench,
    section: "intelligence",
    parentId: "agents",
    build: "placeholder",
  },
  {
    id: "agents.memory",
    path: "/agents/memory",
    label: "Memory",
    title: "Memory",
    description: "Inspectable memory/knowledge access: namespaces, entries, source, and references.",
    icon: Brain,
    section: "intelligence",
    parentId: "agents",
    build: "placeholder",
  },
  {
    id: "agents.schedules",
    path: "/agents/schedules",
    label: "Schedules",
    title: "Schedules",
    description: "Recurring runs and briefs: cadence, next/last run, channel, scope, and failures.",
    icon: CalendarClock,
    section: "intelligence",
    parentId: "agents",
    build: "placeholder",
  },

  // ── Knowledge ─────────────────────────────────────────────────────
  {
    id: "knowledge",
    path: "/knowledge",
    label: "Overview",
    title: "Knowledge",
    description: "Knowledge health, recently updated documents, and missing policy areas.",
    icon: BookOpen,
    section: "intelligence",
    isOverview: true,
    build: "placeholder",
  },
  {
    id: "knowledge.brand-vault",
    path: "/knowledge/brand-vault",
    label: "Brand Vault",
    title: "Brand Vault",
    description: "Document tree with metadata, search, and backlinks.",
    icon: ShieldCheck,
    section: "intelligence",
    parentId: "knowledge",
    build: "placeholder",
  },
  {
    id: "knowledge.sops",
    path: "/knowledge/sops",
    label: "SOPs",
    title: "SOPs",
    description: "SOP library with department, version, effective date, and linked automations.",
    icon: ScrollText,
    section: "intelligence",
    parentId: "knowledge",
    build: "placeholder",
  },
  {
    id: "knowledge.research",
    path: "/knowledge/research",
    label: "Research",
    title: "Research",
    description: "Shared research repository; Marketing Research is a department-filtered lens.",
    icon: FileSearch,
    section: "intelligence",
    parentId: "knowledge",
    build: "placeholder",
  },
  {
    id: "knowledge.documents",
    path: "/knowledge/documents",
    label: "Documents",
    title: "Documents",
    description: "All files with source, type, indexing state, visibility, and freshness.",
    icon: FileBox,
    section: "intelligence",
    parentId: "knowledge",
    build: "placeholder",
  },

  // ── Activity & Traces ─────────────────────────────────────────────
  {
    id: "activity",
    path: "/activity",
    label: "Timeline",
    title: "Activity & Traces",
    description: "Unified event timeline across human, agent, system, connector, and approval events.",
    icon: Activity,
    section: "intelligence",
    isOverview: true,
    build: "built",
  },
  {
    id: "activity.agent-traces",
    path: "/activity/agent-traces",
    label: "Agent Traces",
    title: "Agent Traces",
    description: "Trace explorer from trigger through evidence, tool calls, approval, and result.",
    icon: RouteIcon,
    section: "intelligence",
    parentId: "activity",
    build: "placeholder",
  },
  {
    id: "activity.actions",
    path: "/activity/actions",
    label: "Actions",
    title: "Actions",
    description: "Action ledger: proposed, authorized, executing, succeeded, failed, reconciled.",
    icon: ListChecks,
    section: "intelligence",
    parentId: "activity",
    build: "placeholder",
  },
  {
    id: "activity.errors",
    path: "/activity/errors",
    label: "Errors",
    title: "Errors",
    description: "Failures grouped by user impact and subsystem, with recurrence and owner.",
    icon: AlertTriangle,
    section: "intelligence",
    parentId: "activity",
    build: "placeholder",
  },

  // ── Settings ──────────────────────────────────────────────────────
  {
    id: "settings",
    path: "/settings",
    label: "Overview",
    title: "Settings",
    description: "System and brand setup summary, connection status, and outstanding items.",
    icon: Settings,
    section: "system",
    isOverview: true,
    build: "placeholder",
  },
  {
    id: "settings.stores",
    path: "/settings/stores",
    label: "Stores",
    title: "Stores",
    description: "Store cards with domain, status, currency, timezone, channels, and freshness.",
    icon: Store,
    section: "system",
    parentId: "settings",
    build: "placeholder",
  },
  {
    id: "settings.integrations",
    path: "/settings/integrations",
    label: "Integrations",
    title: "Integrations",
    description: "Connections grouped by commerce, inbox, ads, payments, and channels.",
    icon: Plug,
    section: "system",
    parentId: "settings",
    build: "placeholder",
  },
  {
    id: "settings.team",
    path: "/settings/team",
    label: "Team",
    title: "Team",
    description: "Members, roles, invite status, departments, and activity.",
    icon: Users,
    section: "system",
    parentId: "settings",
    build: "placeholder",
  },
  {
    id: "settings.notifications",
    path: "/settings/notifications",
    label: "Notifications",
    title: "Notifications",
    description: "Rules for in-app, email, and Hermes channel delivery. UI only.",
    icon: Bell,
    section: "system",
    parentId: "settings",
    build: "placeholder",
  },
  {
    id: "settings.appearance",
    path: "/settings/appearance",
    label: "Appearance",
    title: "Appearance",
    description: "Theme, density, sidebar behavior, number/date formats, and reduced motion.",
    icon: Shapes,
    section: "system",
    parentId: "settings",
    build: "placeholder",
  },
  {
    id: "settings.runtime",
    path: "/settings/runtime",
    label: "Runtime",
    title: "Runtime",
    description: "Hermes integration concept: profile status, version, channels, schedule health.",
    icon: Cog,
    section: "system",
    parentId: "settings",
    build: "placeholder",
  },

  // ── Standalone ────────────────────────────────────────────────────
  {
    id: "chat",
    path: "/chat",
    label: "Ask Ecom-OS",
    title: "Ask Ecom-OS",
    description: "Full-page assistant with sessions, citations, and a trace panel. Simulated.",
    icon: Sparkles,
    section: "system",
    build: "built",
  },
  {
    id: "design-system",
    path: "/design-system",
    label: "Design System",
    title: "Design System",
    description: "Reusable components and their states across themes and scenarios.",
    icon: Shapes,
    section: "system",
    build: "built",
  },
];

/** Quick lookups. */
const ROUTE_BY_PATH = new Map(ROUTES.map((r) => [r.path, r]));
const ROUTE_BY_ID = new Map(ROUTES.map((r) => [r.id, r]));

export function getRouteByPath(path: string): RouteMeta | undefined {
  return ROUTE_BY_PATH.get(path);
}

export function getRouteById(id: string): RouteMeta | undefined {
  return ROUTE_BY_ID.get(id);
}

/** Children of a department/parent route, in registry order. */
export function getChildren(parentId: string): RouteMeta[] {
  return ROUTES.filter((r) => r.parentId === parentId);
}

/**
 * Resolve the active route from a pathname. Returns the most specific match:
 * exact route if present, otherwise the deepest ancestor by path prefix.
 */
export function resolveActiveRoute(pathname: string): RouteMeta | undefined {
  const exact = ROUTE_BY_PATH.get(pathname);
  if (exact) return exact;
  // Deepest prefix match (e.g. /finance/orders-margin/ORD-1 -> orders-margin).
  let best: RouteMeta | undefined;
  for (const r of ROUTES) {
    if (pathname === r.path || pathname.startsWith(r.path + "/")) {
      if (!best || r.path.length > best.path.length) best = r;
    }
  }
  return best;
}

/** Breadcrumb chain from department root down to the active route. */
export function getBreadcrumbs(pathname: string): RouteMeta[] {
  const active = resolveActiveRoute(pathname);
  if (!active) return [];
  if (active.parentId) {
    const parent = ROUTE_BY_ID.get(active.parentId);
    return parent ? [parent, active] : [active];
  }
  return [active];
}

export const SECTION_LABELS: Record<RouteSection, string> = {
  core: "Core",
  departments: "Departments",
  intelligence: "Intelligence",
  system: "System",
};
